import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ScreenQueryInfo from "./components/lib/screen-query-info";

// Providers
import AuthProvider from "./providers/AuthProvider";
import { ReactQueryClientProvider } from "./providers/ReactQueryClientProvider";
import ThemeProvider from "./components/ui/theme/theme-provider";

import NextTopLoader from "nextjs-toploader";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <AuthProvider>
              <ReactQueryClientProvider>
                <NextTopLoader />
                {children}
                <Toaster />
                <ScreenQueryInfo />
              </ReactQueryClientProvider>
            </AuthProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
